<div class="container mt-5">
    <div class="row justify-content-center mb-4">
        <div class="col-md-6">
            <h1>Dodaj nowy wpis</h1>
            <?= (isset($errors) ? displayErrors($errors) : '') ?>
        </div>
    </div>

    <div class="row justify-content-center mb-5">
        <div class="col-md-6">
            <form method="post">
                <input type="hidden" name="_token" value="<?= csrfToken('add_phone_book_entry') ?>">
                <div class="form-group mb-4">
                    <label for="firstName">*Imię</label>
                    <input type="text" class="form-control" id="firstName"
                           name="first_name" value="<?= e($entry['first_name'] ?? '') ?>" required>
                </div>
                <div class="form-group mb-4">
                    <label for="lastName">*Nazwisko</label>
                    <input type="text" class="form-control" id="lastName"
                           name="last_name" value="<?= e($entry['last_name'] ?? '') ?>" required>
                </div>
                <div class="form-group mb-4">
                    <label for="phone">*Numer telefonu</label>
                    <input type="tel" class="form-control" id="phone"
                           name="phone" value="<?= e($entry['phone'] ?? '') ?>" required>
                </div>
                <div class="form-group mb-4">
                    <label for="email">*Adres E-mail</label>
                    <input type="email" class="form-control" id="email"
                           name="email" value="<?= e($entry['email'] ?? '') ?>" required>
                </div>
                <div class="form-group mb-4">
                    <label for="address">*Adres</label>
                    <textarea class="form-control" id="address"
                              name="address" required><?= e($entry['address'] ?? '') ?></textarea>
                </div>

                <button type="submit" class="btn btn-primary">Dodaj</button>
                <a href="/" class="btn btn-secondary ms-2">Anuluj</a>
            </form>
        </div>
    </div>
</div>
