<div class="container mt-5">
    <div class="row justify-content-center mb-4">
        <div class="col-md-6">
            <h1>Edytuj wpis</h1>
            <?= (isset($errors) ? displayErrors($errors) : '') ?>
        </div>
    </div>

    <div class="row justify-content-center mb-5">
        <div class="col-md-6">
            <form method="post">
                <input type="hidden" name="_token" value="<?= csrfToken('edit_phone_book_entry_' . $id) ?>">
                <div class="form-group mb-4">
                    <label for="firstName">*Imię</label>
                    <input type="text" class="form-control" id="firstName"
                           name="first_name"
                           value="<?= e($entry['first_name'] ?? $firstName ?? '') ?>" required>
                </div>
                <div class="form-group mb-4">
                    <label for="lastName">*Nazwisko</label>
                    <input type="text" class="form-control" id="lastName"
                           name="last_name"
                           value="<?= e($entry['last_name'] ?? $lastName ?? '') ?>" required>
                </div>
                <div class="form-group mb-4">
                    <label for="phone">*Numer telefonu</label>
                    <input type="tel" class="form-control" id="phone"
                           name="phone"
                           value="<?= e($entry['phone'] ?? $phone ?? '') ?>" required>
                </div>
                <div class="form-group mb-4">
                    <label for="email">*Adres E-mail</label>
                    <input type="email" class="form-control" id="email"
                           name="email"
                           value="<?= e($entry['email'] ?? $email ?? '') ?>" required>
                </div>
                <div class="form-group mb-4">
                    <label for="address">*Adres</label>
                    <textarea class="form-control" id="address"
                              name="address" required><?= e(
                            $entry['address'] ?? $address ?? ''
                        ) ?></textarea>
                </div>

                <button type="submit" class="btn btn-primary">Zapisz</button>
                <a href="/" class="btn btn-secondary ms-2">Anuluj</a>
            </form>
        </div>
    </div>
</div>
